---
# These are Ansible requirements needed to run ceph-ansible main
collections:
  - name: https://opendev.org/openstack/ansible-config_template
    version: 1.2.1
    type: git
  - name: ansible.utils
    version: '>=2.5.0'
  - name: community.general
    version: '==7.5.8'
  - name: ansible.posix
